# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US
tone_instructions: "Provide comprehensive feedback on plugin architecture, security, documentation quality, and code standards. Include actionable suggestions with examples."
early_access: false

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: "use conventional commits structure: <type>[optional scope]: <description>"

  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false
  review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  poem: false

  suggested_labels: true
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: true

  labeling_instructions:
    - label: "security"
      instructions: "Critical security issues including authentication, authorization, injection vulnerabilities, credential management, or data exposure"
    - label: "documentation"
      instructions: "Changes to markdown documentation, README files, or inline code documentation"
    - label: "automation"
      instructions: "Changes to Python scripts in scripts/ directory, mise tasks, or CI/CD workflows"
    - label: "bugfix"
      instructions: "Bug fixes that resolve existing issues or correct incorrect behavior"
    - label: "feature"
      instructions: "New functionality or enhancements to existing features"
    - label: "breaking-change"
      instructions: "Changes that break backward compatibility or require users to update their usage"
    - label: "dependencies"
      instructions: "Updates to Python packages, tool versions, or external dependencies"
    - label: "testing"
      instructions: "Changes to test files, test infrastructure, or testing documentation"

  commit_status: true
  fail_commit_status: false
  review_status: true

  abort_on_close: true
  disable_cache: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
    labels: []
    base_branches: []
