# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US
tone_instructions: "Provide comprehensive feedback on plugin architecture, security, documentation quality, and code standards. Include actionable suggestions with examples."
early_access: false

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: "use conventional commits structure: <type>[optional scope]: <description>"

  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false
  review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  poem: false

  suggested_labels: true
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: true

  labeling_instructions:
    - label: "security"
      instructions: "Critical security issues including authentication, authorization, injection vulnerabilities, credential management, or data exposure"
    - label: "documentation"
      instructions: "Changes to markdown documentation, README files, or inline code documentation"
    - label: "automation"
      instructions: "Changes to Python scripts in scripts/ directory, mise tasks, or CI/CD workflows"
    - label: "bugfix"
      instructions: "Bug fixes that resolve existing issues or correct incorrect behavior"
    - label: "feature"
      instructions: "New functionality or enhancements to existing features"
    - label: "breaking-change"
      instructions: "Changes that break backward compatibility or require users to update their usage"
    - label: "dependencies"
      instructions: "Updates to Python packages, tool versions, or external dependencies"
    - label: "testing"
      instructions: "Changes to test files, test infrastructure, or testing documentation"

  commit_status: true
  fail_commit_status: false
  review_status: true

  abort_on_close: true
  disable_cache: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
    labels: []
    base_branches: []

  path_filters:
    # Exclude virtual environments and caches
    - "!**/.venv/**"
    - "!**/venv/**"
    - "!**/__pycache__/**"
    - "!**/.ruff_cache/**"
    - "!**/.rumdl-cache/**"
    - "!**/.pytest_cache/**"
    - "!**/.mypy_cache/**"

    # Exclude build artifacts
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/.eggs/**"
    - "!**/node_modules/**"

    # Exclude working documents
    - "!docs/plans/**"
    - "!docs/research/**"
    - "!docs/reviews/**"
    - "!docs/notes/**"

    # Exclude examples and templates
    - "!plugins/**/examples/**"
    - "!plugins/**/assets/templates/**"

    # Exclude test fixtures
    - "!tests/fixtures/**"
    - "!**/test/fixtures/**"

    # Include primary directories
    - "scripts/**"
    - "plugins/**"
    - "docs/**"
    - ".claude/**"
    - ".claude-plugin/**"

  path_instructions:
    - path: "scripts/**/*.py"
      instructions: |
        Review Python automation scripts for:
        - Ruff compliance with existing ruff.toml configuration
        - Type hints for all function signatures
        - Google-style docstrings with Args, Returns, and Raises sections
        - Proper error handling with specific exceptions
        - Security: validate inputs, avoid shell injection, handle credentials safely
        - Logging for debugging and monitoring
        - Command-line argument validation

    - path: "plugins/**/.claude-plugin/*.json"
      instructions: |
        Validate plugin manifests for:
        - Required fields present: name, version, description, author, keywords
        - Semantic versioning format (X.Y.Z)
        - JSON schema compliance
        - Accurate dependency specifications
        - Consistency with marketplace registry

    - path: ".claude-plugin/marketplace.json"
      instructions: |
        Critical marketplace registry review:
        - All listed plugins have corresponding directories
        - Plugin metadata matches individual plugin.json files
        - Version numbers are consistent across registry and plugin files
        - No duplicate plugin names or paths
        - Valid JSON structure

    - path: "**/*.sh"
      instructions: |
        Shell script review:
        - Shellcheck compliance
        - Error handling: set -e, set -u, set -o pipefail
        - Input validation and sanitization
        - No hardcoded credentials or sensitive data
        - Clear comments for complex operations

    - path: "plugins/**/skills/**/*.md"
      instructions: |
        Skills documentation quality:
        - Clear skill metadata (name, description)
        - Unambiguous usage instructions
        - Concrete, executable examples
        - Follows skill documentation standards
        - No sensitive information or credentials in examples
        - Proper markdown formatting

    - path: "plugins/**/commands/**/*.md"
      instructions: |
        Slash command documentation:
        - Clear command purpose and use cases
        - Accurate argument specifications
        - Usage examples with expected output
        - Integration notes with other commands if relevant

    - path: "plugins/**/agents/**/*.md"
      instructions: |
        Agent definitions review:
        - Clear agent purpose and capabilities
        - Tool access properly specified
        - Behavioral instructions are unambiguous
        - No conflicting instructions
        - Model specifications follow inheritance pattern (default to inherit from parent)

    - path: "docs/**/*.md"
      instructions: |
        Published documentation standards:
        - Clear, concise technical writing
        - Accurate code examples and commands
        - Proper markdown formatting per .rumdl.toml
        - Valid internal links
        - Examples are up-to-date with current codebase
        - No outdated information

    - path: "{*.toml,*.yaml,*.json}"
      instructions: |
        Configuration file review:
        - Valid syntax for file type
        - Schema compliance where applicable
        - Comments explain non-obvious settings
        - Consistent with project conventions

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  tools:
    # Python tools
    ruff:
      enabled: true
    pylint:
      enabled: true

    # Shell tools
    shellcheck:
      enabled: true

    # Markdown tools
    markdownlint:
      enabled: true

    # YAML tools
    yamllint:
      enabled: true

    # Security scanning
    gitleaks:
      enabled: false
    checkov:
      enabled: true

    # GitHub checks integration
    github-checks:
      enabled: true
      timeout_ms: 90000

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"
      - "plugins/meta/claude-docs/skills/claude-docs/reference/**/*.md"
  learnings:
    scope: auto
  web_search:
    enabled: true
  issues:
    scope: auto
  pull_requests:
    scope: auto

code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: "scripts/**/*.py"
        instructions: "Use Google-style docstrings with Args, Returns, and Raises sections. Type hints in signatures (not docstrings). Include usage examples for complex functions. Focus on behavior and edge cases rather than implementation details."
      - path: "plugins/**/tools/**/*.py"
        instructions: "Brief docstrings focusing on tool purpose and parameters. Include examples for non-obvious usage."
  unit_tests:
    path_instructions:
      - path: "scripts/**/*.py"
        instructions: "Generate tests covering happy paths, error handling, edge cases, and boundary conditions. Use pytest framework. Focus on validating behavior, not implementation details. Mock external dependencies (file I/O, network calls, subprocess). Tests should be independent and not rely on execution order."
