# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US
tone_instructions: "Provide comprehensive feedback on plugin architecture, security, documentation quality, and code standards. Include actionable suggestions with examples."
early_access: false

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: "use conventional commits structure: <type>[optional scope]: <description>"

  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false
  review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  poem: false

  suggested_labels: true
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: true

  commit_status: true
  fail_commit_status: false
  review_status: true

  abort_on_close: true
  disable_cache: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
    labels: []
    base_branches: []
